package io.todorok.contracts;

public enum EventType {
    TASK_SCHEDULED,
    SERIES_CHANGED,
    TASK_CHANGED,
    TASK_ROLLED_OVER,
    ACTIVITY_COMPLETED,
    ACTIVITY_CORRECTED,
    ACTIVITY_SYNC_RESULT,
    ACTIVITY_VOIDED,
    ACTIVITY_SKIPPED,
    PROGRAM_SESSION_REQUESTED,
    ROUTINE_ADVANCED,
    NOTIFICATION_REQUESTED,
    NOTIFICATION_PREFERENCE_CHANGED,
}
